### ISSUE TITLE
Create visualization of data model to finalize design

### ISSUE THREAD

**Issue by laurencecnerual** [greenfield-hippos/backend#1]

**Comment by laurencecnerual** [comment]
notes from today's talk:

table users
id, username, password, isAdmin, email?, account created?, last login?, remaining queries?, salt, hashed pw+salt

table messages
id, isFavorite, foreign key userid, author (QorA), conversation id, timestamp?, content

table conversation 
id, title 

//table conditions (for admins to limit/control chatgpt output)

**Comment by ConwayDecker** [comment]
https://dbdiagram.io/d/671848a297a66db9a3ecc0ae
